export const CLIENT_ID = 'jywCIH1KljuJcJlVpqrYP1OhyOnT1hIpZfLKTEu7';
export const CLIENT_SECRET = 'EW9pQmSvuHIrTju192gJvmWID7kVumwNRFhUsajaSUAJpzTSKdxcGIMqKzjlvYIGBXkTJUiZ8EFylJ9PUZfxS9iVcv4aq3SJkuuPG1cYjdROBwjKCatAci4dVsvnGhOp';
