name: CI/CD

on:
  push:
  pull_request:
    
jobs:
  build:
    name: Build EEG Authentication
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2.4.2
      
      - name: Setup JDK 19
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '19'
          distribution: 'adopt'
          architecture: x64
          
      - name: Maven Build
        run: mvn -DskipTests=true --batch-mode --update-snapshots package
      
      - name: Upload Built Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: artifact
          path: eeg_backend/target/eeg_backend-*.jar
  
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy Bronco Projects
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3.0.0
        with:
         name: artifact
       
      - name: Deploy to AWS Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: us-west-1
          application_name: EEG Authentication
          environment_name: Eegauthentication-env-1
          version_label: ${{github.SHA}}
          use_existing_version_if_available: true
          deployment_package: eeg_backend-0.0.1-SNAPSHOT.jar
